### ISSUE TITLE
missing results compared to the website search

### ISSUE THREAD

**Issue by luitoz** [daneski13/linkedin-job-scraper#2]
I want to extract the results from this url : [https://www.linkedin.com/jobs/search?f_TPR=r2592000&keywords=java&location=Jefferson%20County%2C%20Alabama%2C%20United%20States&f_WT=2&f_E=4&sortBy=R&geoId=105185483](url) 
the website shows 7K results
![image](https://github.com/daneski13/linkedin-job-scraper/assets/19673949/ca6d3fe8-ebaf-49ee-b990-55b386e59bf9)
but when I run the script, it only extracts few results(30):
`python3 scrape.py

Scraping...:   0%|                                                                           | 0/30 [00:00<?, ?it/s]`

**Comment by daneski13** [comment]
Interesting, on my end it is displaying 31 jobs for that link. This scraper assumes no user is currently logged into LinkedIn so be sure to logout. It's not generally a good idea to scrape from a user account as that is against TOS and may lead to a banned or suspended LinkedIn account.

<img width="1157" alt="Screenshot 2024-02-06 at 3 19 05 PM" src="https://github.com/daneski13/linkedin-job-scraper/assets/44625507/58c9478a-d94e-4a42-ad94-f2f09de213a8">

**Comment by luitoz** [comment]
Thanks for responding quickly!
have you considered implementing an authenticated session functionality to extract all the results shown by the website?
to avoid getting banned from LinkedIn, users would use an alternative account only for scrape purposes.
I tried to use the LI_AT_COOKIE environment variable to simulate an authenticated session, but it didn't work

**Comment by C-Nubela** [comment]
Hello there @luitoz,

I work at Proxycurl, a B2B data provider and API and we could help you search for job listings. We are paid, but you won't have to worry about proxies, account bans, or any of the headaches with self-hosted scrapers like this honorable project.

[Consider giving our Job Search Endpoint here a go](https://nubela.co/proxycurl/jobs-api?utm_campaign=content_amplification&utm_source=github&utm_medium=social&utm_content=comments)(free trial credits are available).

**Comment by haghani2** [comment]
Recently noticed that if you are scraping with specific url and you are not logged in, when going through every single listing some of them don't show any expanded description of the listing and I can only see the block listings on the left and most of the expanded listings on the right is missing. Is it just me or it happens to anyone else? Thanks

**Comment by daneski13** [comment]
Using a separate account for scraping (and using a user account to scrape in general) is heavily against the TOS and is not something I will support.

> some of them don't show any expanded description of the listing and I can only see the block listings on the left and most of the expanded listings on the right is missing.

This is a bug on LinkedIn's end, some sort-of problem with their client-side rendering, potentially even intentional to discourage scraping.
